package org.jboss.qa.bpms.traffic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private org.jboss.qa.bpms.traffic.Driver driver;
	private java.lang.String manufacturer;
	private java.lang.String model;
	private java.lang.Integer year;
	private java.lang.String license;

	public Car() {
	}

	public org.jboss.qa.bpms.traffic.Driver getDriver() {
		return this.driver;
	}

	public void setDriver(org.jboss.qa.bpms.traffic.Driver driver) {
		this.driver = driver;
	}

	public java.lang.String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(java.lang.String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public java.lang.String getModel() {
		return this.model;
	}

	public void setModel(java.lang.String model) {
		this.model = model;
	}

	public java.lang.Integer getYear() {
		return this.year;
	}

	public void setYear(java.lang.Integer year) {
		this.year = year;
	}

	public java.lang.String getLicense() {
		return this.license;
	}

	public void setLicense(java.lang.String license) {
		this.license = license;
	}

	public Car(org.jboss.qa.bpms.traffic.Driver driver,
			java.lang.String manufacturer, java.lang.String model,
			java.lang.Integer year, java.lang.String license) {
		this.driver = driver;
		this.manufacturer = manufacturer;
		this.model = model;
		this.year = year;
		this.license = license;
	}

}