package org.jboss.qa.bpms.traffic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Driver implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.Integer age;
	private java.lang.String city;
	private java.lang.String country;
	private java.lang.Integer points;
	private java.lang.String status;

	private java.util.List<java.lang.Integer> phone;

	private boolean insured;

	private org.jboss.qa.bpms.traffic.Insurance insurance;

	public Driver() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.Integer getPoints() {
		return this.points;
	}

	public void setPoints(java.lang.Integer points) {
		this.points = points;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.util.List<java.lang.Integer> getPhone() {
		return this.phone;
	}

	public void setPhone(java.util.List<java.lang.Integer> phone) {
		this.phone = phone;
	}

	public boolean isInsured() {
		return this.insured;
	}

	public void setInsured(boolean insured) {
		this.insured = insured;
	}

	public org.jboss.qa.bpms.traffic.Insurance getInsurance() {
		return this.insurance;
	}

	public void setInsurance(org.jboss.qa.bpms.traffic.Insurance insurance) {
		this.insurance = insurance;
	}

	public Driver(java.lang.String name, java.lang.Integer age,
			java.lang.String city, java.lang.String country,
			java.lang.Integer points, java.lang.String status,
			java.util.List<java.lang.Integer> phone, boolean insured,
			org.jboss.qa.bpms.traffic.Insurance insurance) {
		this.name = name;
		this.age = age;
		this.city = city;
		this.country = country;
		this.points = points;
		this.status = status;
		this.phone = phone;
		this.insured = insured;
		this.insurance = insurance;
	}

}
