package org.jboss.qa.bpms.traffic;

import java.time.OffsetDateTime;
import java.util.Date;
import java.time.LocalDate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Fine implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer points;
	private java.lang.Integer amount;

	private boolean paidInGracePeriod;

	private LocalDate paidDate;

	public Fine() {
	}

	public java.lang.Integer getPoints() {
		return this.points;
	}

	public void setPoints(java.lang.Integer points) {
		this.points = points;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public boolean isPaidInGracePeriod() {
		return this.paidInGracePeriod;
	}

	public void setPaidInGracePeriod(boolean paidInGracePeriod) {
		this.paidInGracePeriod = paidInGracePeriod;
	}

	public java.time.LocalDate getPaidDate() {
		return this.paidDate;
	}

	public void setPaidDate(java.time.LocalDate paidDate) {
		this.paidDate = paidDate;
	}

	public Fine(java.lang.Integer points, java.lang.Integer amount,
			boolean paidInGracePeriod, java.time.LocalDate paidDate) {
		this.points = points;
		this.amount = amount;
		this.paidInGracePeriod = paidInGracePeriod;
		this.paidDate = paidDate;
	}

}