package org.jboss.qa.bpms.traffic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Insurance implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long id;

	public Insurance() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Insurance(java.lang.Long id) {
		this.id = id;
	}

}