package org.jboss.qa.bpms.traffic;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Violation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer speed;
	private java.lang.Integer limit;
	private java.lang.String type;
	private java.lang.String code;
	private java.time.LocalDate date;

	public Violation() {
	}

	public java.lang.Integer getSpeed() {
		return this.speed;
	}

	public void setSpeed(java.lang.Integer speed) {
		this.speed = speed;
	}

	public java.lang.Integer getLimit() {
		return this.limit;
	}

	public void setLimit(java.lang.Integer limit) {
		this.limit = limit;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.time.LocalDate getDate() {
		return this.date;
	}

	public void setDate(java.time.LocalDate date) {
		this.date = date;
	}

	public Violation(java.lang.Integer speed, java.lang.Integer limit,
			java.lang.String type, java.lang.String code,
			java.time.LocalDate date) {
		this.speed = speed;
		this.limit = limit;
		this.type = type;
		this.code = code;
		this.date = date;
	}

}
